name: mi_card
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  linkable: ^1.0.4
  url_launcher: ^5.4.10
  flutter_launcher_icons: "^0.9.2"



flutter:

  uses-material-design: true
  assets:
    - LiquidColour.jpg

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: FiraSans
      fonts:
        - asset: fonts/FiraSans-Regular.ttf
